[package]
name = "baxe"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
baxe-core = { path = "crates/core", version = "0.1.0" }
baxe-derive = { path = "crates/derive", version = "0.1.0" }
