[package]
name = "baxe-derive"
version = "0.1.6"
edition = "2021"
description = "Procedural macro for Baxe library."
license = "MIT"
repository = "https://github.com/zyphelabs/baxe"

[lib]
proc-macro = true

[dependencies]
syn = "2"
quote = "1"
proc-macro2 = "1"
